"""
Generates a filled-in ProjectChecklist PDF that mirrors the official
ProjectChecklistSp26.pdf items with check marks.
"""
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.enums import TA_LEFT


def mk_style(name, **kwargs):
    base = getSampleStyleSheet()["BodyText"]
    return ParagraphStyle(name=name, parent=base, **kwargs)


HEADING = mk_style("heading", fontName="Helvetica-Bold", fontSize=13, spaceBefore=10, spaceAfter=6, alignment=TA_LEFT)
POINTS = mk_style("points", fontName="Helvetica-Oblique", fontSize=10, spaceBefore=2, spaceAfter=4, alignment=TA_LEFT)
ITEM = mk_style("item", fontName="Helvetica", fontSize=11, leading=15, alignment=TA_LEFT)
TITLE = mk_style("title", fontName="Helvetica-Bold", fontSize=15, spaceAfter=10, alignment=TA_LEFT)
SUB = mk_style("sub", fontName="Helvetica", fontSize=10, spaceAfter=8, alignment=TA_LEFT)


def item(text):
    return Paragraph(f"[<b>X</b>] {text}", ITEM)


def main(out_path):
    doc = SimpleDocTemplate(
        out_path, pagesize=letter,
        leftMargin=54, rightMargin=54, topMargin=54, bottomMargin=54,
    )
    flow = []
    flow.append(Paragraph("CS336 Project Checklist - Group 1", TITLE))
    flow.append(Paragraph(
        "Online Travel Reservation System. Each item below from "
        "ProjectChecklistSp26.pdf has been implemented in this submission.",
        SUB,
    ))

    flow.append(Paragraph("1. User functionality", HEADING))
    flow.append(Paragraph("(20 points)", POINTS))
    flow.append(item("let people search for flights between two airports"))
    flow.append(item("one way on a specific date"))
    flow.append(item("round-trip on specific dates"))
    flow.append(item("one way or roundtrip on flexible dates (+/- 3 days)"))
    flow.append(item("browse the resulting flights"))
    flow.append(item("sort flights by different criteria (price, take-off time, landing time, duration of flight)"))
    flow.append(item("filter the list of flights by various criteria (price, number of stops, airline, take-off time, landing time)"))
    flow.append(Spacer(1, 6))
    flow.append(Paragraph("(20 points)", POINTS))
    flow.append(item("Browse questions and answers"))
    flow.append(item("Search questions and answers by keywords"))
    flow.append(item("make flight reservations / buy the ticket"))
    flow.append(item("enter the waiting list if the flight is full"))
    flow.append(item("view all the past flight reservations with their details"))
    flow.append(item("view all the upcoming flights with their details"))
    flow.append(item("cancel their flight reservations (if it is business or first class)"))
    flow.append(item("send an alert to customers in the waiting list that there is an empty seat"))
    flow.append(item("post questions to the customer representative"))

    flow.append(Paragraph("2. Admin (account created ahead of time)", HEADING))
    flow.append(Paragraph("(20 points)", POINTS))
    flow.append(item("Add, Edit information and Delete a customer representative or customer"))
    flow.append(item("Obtain a sales report for a particular month"))
    flow.append(item("Produce a list of reservations by flight number or by customer name"))
    flow.append(item("Produce a summary listing of revenue generated by a particular flight, airline, or customer"))
    flow.append(item("Find out which customer generated most total revenue"))
    flow.append(item("Produce a list of most active flights (most tickets sold)"))

    flow.append(Paragraph("3. Customer Representative", HEADING))
    flow.append(Paragraph("(20 points)", POINTS))
    flow.append(item("Make flight reservations on behalf of users"))
    flow.append(item("Edit flight reservations for a customer"))
    flow.append(item("Add, Edit, Delete information for aircrafts, airports, and flights"))
    flow.append(item("Retrieve a list of all the passengers who are on the waiting list of a particular flight"))
    flow.append(item("Produce a list of all flights for a given airport (departing and arriving)"))
    flow.append(item("Reply to user's questions"))

    flow.append(Paragraph("4. ER Diagram / Relational Schema", HEADING))
    flow.append(Paragraph("(20 points)", POINTS))
    flow.append(item("ER diagram / Relational Schema submitted on time (Project - deliverable 1)"))

    doc.build(flow)


if __name__ == "__main__":
    main("Group-1-ProjectChecklist.pdf")
    print("Wrote Group-1-ProjectChecklist.pdf")
